platform: linux

image_resource:
  type: docker-image
  source:
    repository: wingrunr21/alpine-heroku-cli
    tag: "latest"

params:
  heroku_email:
  heroku_api_token:
  app_name:

run:
  path: sh
  dir: .
  args:
    - -exc
    - |
      cat > /root/.netrc <<EOF
      machine api.heroku.com
          login ${heroku_email}
          password ${heroku_api_token}
      machine git.heroku.com
          login ${heroku_email}
          password ${heroku_api_token}
      EOF
      export HEROKU_API_KEY=${heroku_api_token}
      heroku container:release web -a ${app_name}